# Makefile for Windows

CC = cl -nologo
LD = cl -nologo
CFLAGS = -DWIN32
LDFLAGS = Rpcrt4.lib Shlwapi.lib
O = .obj
A = .lib
E = .exe
CONFIG_H = config.h
BUILD_DIR = %cd%
S = sys^\
U = utils^\
7CC = 7cc$E
CC1 = cc1$E

UTILS_OBJ = $Uwrapper$O \
          $Ustrbuf$O \
          $Uvector$O \
          $Umap$O \
          $Ustring$O \
          $Uset$O

UTILS_INC = $Ustrbuf.h \
          $Uvector.h \
          $Umap.h \
          $Uset.h \
          $Uutils.h

SYS_OBJ = $Swinnt$O
SYS_INC = $Ssys.h

CC1_OBJ = alloc$O \
        ast$O \
        cc$O \
        cpp$O \
        print$O \
        decl$O \
        error$O \
        eval$O \
        expr$O \
        gen$O \
        lex$O \
        stmt$O \
        sym$O \
        type$O \
        input$O \
        ir$O \
        block$O \
        hideset$O \
        imap$O

CC1_INC = cc.h \
        ast.h \
        7cc.h \
        lex.h \
        gen.h \
        node.def \
        token.def \
        rop.def \
        hideset.h \
        imap.h

7CC_OBJ = 7cc$O

TOOLS_EXE = ntenv$E

all: $(7CC) $(CC1)

$(7CC): $(7CC_OBJ) $(UTILS_OBJ) $(SYS_OBJ)
        $(LD) $(LDFLAGS) -Fe$@ $(7CC_OBJ) $(UTILS_OBJ) $(SYS_OBJ)

$(CC1): $(CC1_OBJ) $(UTILS_OBJ) $(SYS_OBJ)
        $(LD) $(LDFLAGS) -Fe$@ $(CC1_OBJ) $(UTILS_OBJ) $(SYS_OBJ)

$(UTILS_OBJ): $(UTILS_INC) $(CONFIG_H)

$Uwrapper$O:  $Uwrapper.c;      $(CC) $(CFLAGS) -c -Fo$@ $Uwrapper.c
$Ustrbuf$O:   $Ustrbuf.c;       $(CC) $(CFLAGS) -c -Fo$@ $Ustrbuf.c
$Uvector$O:   $Uvector.c;       $(CC) $(CFLAGS) -c -Fo$@ $Uvector.c
$Umap$O:      $Umap.c;          $(CC) $(CFLAGS) -c -Fo$@ $Umap.c
$Ustring$O:   $Ustring.c;       $(CC) $(CFLAGS) -c -Fo$@ $Ustring.c
$Uset$O:      $Uset.c;          $(CC) $(CFLAGS) -c -Fo$@ $Uset.c

$(SYS_OBJ): $(SYS_INC) $(CONFIG_H)

$Swinnt$O:    $Swinnt.c;        $(CC) $(CFLAGS) -c -Fo$@ $Swinnt.c

$(CC1_OBJ): $(CC1_INC) $(CONFIG_H)

alloc$O:    	alloc.c;    	$(CC) $(CFLAGS) -c -Fo$@ alloc.c
ast$O:		ast.c;		$(CC) $(CFLAGS) -c -Fo$@ ast.c
cc$O:		cc.c;		$(CC) $(CFLAGS) -c -Fo$@ cc.c
cpp$O:		cpp.c;		$(CC) $(CFLAGS) -c -Fo$@ cpp.c
print$O:	print.c;	$(CC) $(CFLAGS) -c -Fo$@ print.c
decl$O:		decl.c;		$(CC) $(CFLAGS) -c -Fo$@ decl.c
error$O:	error.c;	$(CC) $(CFLAGS) -c -Fo$@ error.c
eval$O:		eval.c;		$(CC) $(CFLAGS) -c -Fo$@ eval.c
expr$O:		expr.c;		$(CC) $(CFLAGS) -c -Fo$@ expr.c
gen$O:		gen.c;		$(CC) $(CFLAGS) -c -Fo$@ gen.c
lex$O:		lex.c;		$(CC) $(CFLAGS) -c -Fo$@ lex.c
stmt$O:		stmt.c;		$(CC) $(CFLAGS) -c -Fo$@ stmt.c
sym$O:		sym.c;		$(CC) $(CFLAGS) -c -Fo$@ sym.c
type$O:		type.c;		$(CC) $(CFLAGS) -c -Fo$@ type.c
input$O:	input.c;	$(CC) $(CFLAGS) -c -Fo$@ input.c
ir$O:		ir.c;		$(CC) $(CFLAGS) -c -Fo$@ ir.c
block$O:	block.c;	$(CC) $(CFLAGS) -c -Fo$@ block.c
hideset$O:	hideset.c;	$(CC) $(CFLAGS) -c -Fo$@ hideset.c
imap$O:		imap.c;		$(CC) $(CFLAGS) -c -Fo$@ imap.c

ntenv$E:        $Sntenv.c;      $(CC) $(CFLAGS) -Fe$@ $Sntenv.c

$(CONFIG_H): $(TOOLS_EXE)
        @ntenv$E "$(BUILD_DIR)" > $@

clean::
        @del /q *$O $S*$O $U*$O
        @del /q $(7CC) $(CC1)
        @del /q ntenv$E

distclean:: clean
        @del /q $(CONFIG_H)