// tranform Windows path
#include <stdio.h>
#include <stdlib.h>

// version
#define VERSION "0.3.0-dev"

static char *repl(char *arg)
{
    int len = strlen(arg);
    char *out = malloc(len * 2 + 1);
    char *d = out;
    for (int i = 0; i < len; i++) {
        char c = arg[i];
        if (c == '\\') {
            char c1 = i + 1 < len ? arg[i+1] : 0;
            if (c1 == '\\') {
                *d++ = c;
                *d++ = c1;
                i++;
            } else {
                *d++ = '\\';
                *d++ = '\\';
            }
        } else {
            *d++ = c;
        }
    }
    *d++ = '\0';
    return out;
}

int main(int argc, char *argv[])
{
    char *pwd, *inc, *lib;
    char *pwd1, *inc1, *lib1;

    pwd = argv[1];
    inc = getenv("INCLUDE");
    lib = getenv("LIBPATH");

    pwd1 = repl(pwd);
    inc1 = repl(inc);
    lib1 = repl(lib);

    printf("/* Auto-generated by makefile. */\n");
    printf("#ifndef _CONFIG_H\n");
    printf("#define _CONFIG_H\n");
    printf("\n");
    printf("#define VERSION \"%s\"\n", VERSION);
    printf("#define CONFIG_WINNT\n");
    printf("#define BUILD_DIR \"%s\"\n", pwd1);
    printf("#define NT_INCLUDE_DIR \"%s\"\n", inc1);
    printf("#define NT_LIB_DIR \"%s\"\n", lib1);
    printf("\n");
    printf("#endif\n");

    return 0;
}
